# Generated by Django 3.0.5 on 2020-04-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='上班时间')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='下班班时间')),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
    ]
