# Generated by Django 3.0.5 on 2020-04-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('userCode', models.CharField(max_length=20)),
                ('attendType', models.CharField(choices=[('1', '上班打卡'), ('2', '下班打卡')], default='1', max_length=10, verbose_name='打卡类型')),
                ('attendState', models.CharField(choices=[('1', '正常 '), ('2', '迟到'), ('3', '早退')], default='1', max_length=10, verbose_name='打卡状态')),
                ('pushTime', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('pushEndTime', models.DateTimeField(auto_now=True, verbose_name='下班打卡时间')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'card_table',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('userCode', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('1', '男 '), ('2', '女')], default='1', max_length=10, verbose_name='性别')),
                ('attendState', models.CharField(choices=[('1', '在职'), ('2', '离职')], default='1', max_length=10, verbose_name='打卡状态')),
                ('insertTime', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('userCode', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('1', '男 '), ('2', '女')], default='1', max_length=10, verbose_name='性别')),
                ('attendState', models.CharField(choices=[('1', '在职'), ('2', '离职')], default='1', max_length=10, verbose_name='打卡状态')),
                ('insertTime', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
