# Generated by Django 3.0.5 on 2020-04-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_attendcard_user_usertable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
