# Generated by Django 3.0.5 on 2020-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_attendcard_pushendtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='attendState',
        ),
        migrations.AddField(
            model_name='usertable',
            name='state',
            field=models.CharField(choices=[('1', '在职'), ('2', '离职')], default='1', max_length=10, verbose_name='在职状态'),
        ),
    ]
