# Generated by Django 3.0.5 on 2020-04-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200415_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendcard',
            name='attendState',
            field=models.CharField(choices=[('1', '正常 '), ('2', '迟到'), ('3', '早退'), ('4', '缺卡')], default='1', max_length=10, verbose_name='打卡状态'),
        ),
    ]
