# Generated by Django 3.0.5 on 2020-04-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200416_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendcard',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendFace', verbose_name='打卡证据图片'),
        ),
    ]
